apiVersion: v2
name: devops-web
description: Moje webová aplikace pro Harness demo
type: application

# Verze samotného Chartu (měníš, když měníš šablony)
version: 0.1.0

# Verze tvojí aplikace (co skutečně běží uvnitř - např. tag z Dockeru)
appVersion: "1.0.0"
