apiVersion: v2
name: devops-web
description: DevOps Web Application - Flask-based contact form and admin panel
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flask
  - python
  - web
maintainers:
  - name: Tomas Jartymyk
